depot/config/routes.rb
Rails.application.routes.draw do
  constraints user_agent: /Firefox/ do
    root 'store#index', via: :all
    match '*path', to: redirect('404'), via: :all
  end

  get 'admin' => 'admin#index'

  namespace :admin do
    get 'reports' => 'reports#index'
    get 'categories' => 'categories#index'
    get 'categories/:id/books' => 'categories#products', as: :category_books, id: '/\d/'
    get 'categories/:id/books', to: redirect('/')
  end


  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'my-orders' => 'users#orders'
  get 'my-items' => 'users#line_items'

  resources :users

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    resources :products, path: 'books'
    resources :categories
    root 'store#index', as: 'store_index', via: :all
  end


  resources :products do
    get :who_bought, on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

depot/app/views/layouts/abhishek.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <div id="main">
    <%= yield %>
  </div>
</body>
</html>

depot/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <div id="main">
    <%= yield %>
  </div>
</body>
</html>

depot/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Depot</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='<%= controller.controller_name %>'>
    <div id="banner">
      <%= form_tag store_index_path, class: 'locale' do %>
        <%= select_tag 'set_locale',
          options_for_select(LANGUAGES, I18n.locale.to_s),
              onchange: 'this.form.submit()' %>
        <%= submit_tag 'submit' %>
        <%= javascript_tag "$('.locale input').hide()" %>
      <% end %>
      <%= image_tag 'logo.svg', alt: 'The Pragmatic Bookshelf' %>
      <span class="title"><%= @page_title %></span>
    </div>
    <div id="columns">
      <div id="side">
        <div id="cart">
          <% if @cart %>
            <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
              <%= render(@cart) %>
            <% end %>
          <% end %>
        </div>
        <ul>
          <li><%= link_to t('.home'), store_index_url %></li>
          <li><a href="http://www..../faq"><%= t('.questions') %></a></li>
          <li><a href="http://www..../news"><%= t('.news') %></a></li>
          <li><a href="http://www..../contact"><%= t('.contact') %></a></li>
          <li><a><%= t('.time') %> <%= Time.now.strftime("%I:%M%p") %></a></li>
        </ul>
        <% if current_user %>
          <ul>
            <li><%= link_to t('.orders'), orders_url %></li>
            <li><%= link_to t('.products'), products_url %></li>
            <li><%= link_to t('.users'), users_url %></li>
            <li><%= link_to t('.edit_profile'), edit_user_url(current_user) %></li>
          </ul>
          <%= button_to t('.logout'), logout_url, method: :delete %>
        <% else %>
          <%= button_to t('.login'), login_url, method: :get %>
        <% end %>
      </div>
      <div id="main">
        <%= yield %>
      </div>
    </div>
    <footer>
      <h4>Your IP Address is : <%= request.remote_ip %></h4>
      <h4>Hit Counter: <%= pageviews %></h4>
    </footer>
  </body>
</html>

depot/app/views/layouts/my_profile.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <div id="main">
    <%= yield %>
  </div>
</body>
</html>